version: "3.8"


services:
  mongodb-local:
    image: mongo:latest
    build:
        context: .
        dockerfile: mongodb-setup.dockerfile
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data:
    driver: local
    driver_opts:
      type: none
      device: "D:\\Docker\\MongoDb"
      o: bind
